export const MOVIES_ROUTES = {
  HOME: { path: '/', title: '' },
  MOVIES: { path: '/movies', title: 'Фильмы' },
  SERIALS: { path: '/serials', title: 'Сериалы' },
  ANIMATIONS: { path: '/animations', title: 'Мультфильмы' },
  DETAILS_MOVIE: { path: '/movies/:id', title: '' },
  POPULAR: { path: '/popular', title: 'Популярные фильмы' },
  BEST: { path: '/best', title: 'ТОП 250 лучших фильмов' },
  POPULAR_SERIALS: { path: '/popular-serials', title: 'Популярные сериалы' },
  PREMIERES: { path: '/premieres', title: 'Кинопремьеры' },
  FAMILY_MOVIES: { path: '/family', title: 'Семейные фильмы' },
  ROMANTIC_MOVIES: { path: '/romantic', title: 'Романтика' },
  ZOMBIE_MOVIES: { path: '/zombie', title: 'Зомби' },
  CATASTROPHE_MOVIES: { path: 'catastrophe', title: 'Катастрофы' },
  COMICS_MOVIES: { path: '/comics', title: 'Комиксы' },
} as const;
